version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    target-branch: "develop"
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"

      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
